FROM maven:3.6.0-jdk-11-slim AS builder #change base image
WORKDIR /app
COPY src /app/src #change path
COPY pom.xml /app
RUN mvn -f /app/pom.xml clean package #change to gradle


FROM adoptopenjdk/openjdk11
RUN apt-get update && apt-get install -y iputils-ping #remove
WORKDIR /app
COPY --from=builder /app/target/account-service-0.0.1-SNAPSHOT.jar /usr/local/lib/account.jar #change path
EXPOSE 8091 #change port
ENTRYPOINT ["java","-Xmx128m","-jar","/usr/local/lib/account.jar"] #change start comand
